# Generated by Django 4.1.5 on 2023-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledetails",
            name="Phone",
            field=models.CharField(max_length=10),
        ),
    ]
